### ISSUE TITLE
Add crops page with user id

### ISSUE THREAD

**Issue by Ajitkhadka123** [Ajitkhadka123/Agriculture-Information-Management-System#1]
![image](https://user-images.githubusercontent.com/101698296/162756539-90f5d622-f29a-405c-9fbb-251d7c6cb149.png)

**Comment by Alis-Tamang** [comment]
Here is the solved version of add crops
![issue](https://user-images.githubusercontent.com/103161433/162765566-a7f2ec1b-1920-4675-b0fe-ec29e47adb81.PNG)
