### ISSUE TITLE
Issue Found in AdminSection

### ISSUE THREAD

**Issue by Alis-Tamang** [Ajitkhadka123/Agriculture-Information-Management-System#10]
![image](https://user-images.githubusercontent.com/103161433/176982402-baa1a444-8252-49c0-a14f-6f01583d31ea.png)

**Comment by mgrsandeep** [comment]
![solved](https://user-images.githubusercontent.com/101698577/177000557-5a87a619-7a0b-4d89-89d9-29bb6dd4911b.png)
![Screenshot (778)](https://user-images.githubusercontent.com/101698577/177000561-dff9c098-4f1b-4a96-81e3-acf7e8a50b7a.png)

**Comment by mgrsandeep** [comment]
Issue solved by importing jar file and casting resultSetToTableModel to DbUtils.
