### ISSUE TITLE
Logo in Login page / password field in Create Account 

### ISSUE THREAD

**Issue by Alis-Tamang** [Ajitkhadka123/Agriculture-Information-Management-System#2]
Insert Logo in Log in page and change the password field in create account.

 
![277926852_2130693660430587_6826911546206479275_n](https://user-images.githubusercontent.com/103161433/162757146-af4f3600-6426-443f-872d-192d267fce41.png)

![277593203_506129717850654_5687104900179716589_n](https://user-images.githubusercontent.com/103161433/162759486-1421d134-1567-424d-8311-3ef4b77eeb93.png)

**Comment by Ajitkhadka123** [comment]
I have updated the code u can check now
