### ISSUE TITLE
Privacy

### ISSUE THREAD

**Issue by 4aanG** [Ajitkhadka123/Agriculture-Information-Management-System#4]
![Screenshot (142)](https://user-images.githubusercontent.com/101698349/166407569-f8c95ce4-392f-4f91-aa97-809553fe529d.png)

Hi! guys as you can see when I type the password the words does not hide, please refine it so the words hides when the Admin type the password for the privacy.

**Comment by Ajitkhadka123** [comment]
![image](https://user-images.githubusercontent.com/101698296/166718626-7218e0ca-38fc-40d5-9b99-174071203c85.png)



the issue is solved
