### ISSUE TITLE
Main error while running the code

### ISSUE THREAD

**Issue by 4aanG** [Ajitkhadka123/Agriculture-Information-Management-System#5]
Can you please look at this error, the program does not run because of it.

![Screenshot (197)](https://user-images.githubusercontent.com/101698349/167543397-8f6bb3ef-7033-4155-9a0a-c236c7a2f03f.png)

**Comment by Ajitkhadka123** [comment]
this can be overcomed by selecting the main file

**Comment by Ajitkhadka123** [comment]
named loading.java
