### ISSUE TITLE
Privacy error

### ISSUE THREAD

**Issue by 4aanG** [Ajitkhadka123/Agriculture-Information-Management-System#6]
Previously I had posted this same issue but it was on admin 'create account' then and now this time it's on municipality create account', I request you to solver this issue to maintain privacy for the user.
P.S. look at the password it's suppose to hide but it does not.
![Screenshot (198)](https://user-images.githubusercontent.com/101698349/167601755-224208b0-3b56-42ad-8691-8d8dd8a70001.png)

**Comment by Ajitkhadka123** [comment]
![image](https://user-images.githubusercontent.com/101698296/168430454-1d8d6ec5-3611-49c0-9f90-eab72b36ab71.png)

The issue have been solved and files are updated
